repos:
  - repo: https://github.com/realm/SwiftLint
    rev: 0.55.1
    hooks:
      - id: swiftlint
        name: SwiftLint for MusicSpot v2
        entry: swiftlint lint --fix --strict "iOS/MusicSpot_v2/"
        language: swift
        always_run: true
