# 한 라인 길이 제한
line_length:
    warning: 120 #default: 120
    error: 200
    
# 강제 형변환
force_cast: error
force_try: error

# 의미없는 공백/줄 바꿈
trailing_newline: warning
trailing_whitespace:
    severity: warning
    ignores_empty_lines: true
    
# 함수 길이 제한
function_body_length:
    warning: 50
    error: 100
    
# 타입 지정 시, 이름 조건
type_name:
    min_length:
        warning: 3
        error: 0
    max_length:
        warning: 40
        error: 1000
