# workflow 의 이름
name: Xcode Test

env:
  PROJECT: 'MaybeGamsung'

on:
  # Epic 브랜치에 pull request 이벤트가 일어났을때 해당 workflow 를 trigger
  pull_request:
    branches: [ '**/epic/iOS/**' ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    # uses 키워드를 통해 Github Actions에서 기본으로 제공하는 액션을 사용 가능. 아래 액션은 repository 에 체크아웃하는 것
    - uses: actions/checkout@v2
    # shell 이용해서 하나의 command 수행
    - name: 🛠 Start xcode build
      env:
        XCODEPROJ: "iOS/${{ env.PROJECT }}/${{ env.PROJECT }}.xcodeproj"
      run: |
        xcodebuild clean test
        -project ${{ env.XCODEPROJ }}
        -scheme ${{ env.PROJECT }}
        -destination 'platform=iOS Simulator,name=${{ matrix.simulator }},OS=latest'