name: Xcode_build_test

on:
  push:
    branches: ['iOS/epic/xcode-ci']
  pull_request:
    branches:
      - 'iOS/release'
      - 'iOS/epic/**'
    types: [assigned, labeled, opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: macos-13
    env:
      working-directory: ./iOS
    strategy:
      matrix:
        package: [MSCoreKit, MSFoundation, MSUIKit]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Xcode Setup
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
    
    - name: Build ${{ matrix.package }}
      run: xcodebuild \
        -scheme ${{ matrix.package }} \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 15' \
        build

    - name: Test ${{ matrix.package }}
      run: xcodebuild test \
        -scheme ${{ matrix.package }} \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0'
